name: Cypress Testing
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm install -f

      - name: Run E2E tests 🧪
        uses: cypress-io/github-action@v4
        with:
          # we have already installed everything
          install: false
          working-directory: cypress/e2e
          browser: headless

      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v4
        with:
          # we have already installed everything
          install: false
          # to run component tests we need to use "component: true"
          component: true
